[tool.poetry]
name = "pal_bolts"
version = "0.1.0"
description = ""
authors = ["Oliver Thomas <1835492+olliethomas@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
torchvision = "0.9"
lightning-bolts = "^0.3.1"
torch = "1.8"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
pydocstyle = "^5.1.1"
pytest = "^6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py38']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
[tool.isort]
known_third_party = [
  "PIL",
  "hydra",
  "omegaconf",
  "pandas",
  "pytorch_lightning",
  "torch",
  "torchvision",
  "tqdm",
  "wandb",
]
known_future_library = []
extra_standard_library = ["dataclasses", "__future__"]
line_length = 88
profile = "black"
force_sort_within_sections = "True"
classes = ["MISSING"]
